
export interface StudyFile {
  id: string;
  name: string;
  type: string;
  size: string;
  content: string;
  uploadDate: Date;
  isVirtual?: boolean; // True if generated by AI
}

export enum MessageRole {
  USER = 'user',
  MODEL = 'model',
  ASSISTANT = 'assistant'
}

export interface Message {
  id: string;
  role: MessageRole | 'user' | 'assistant';
  text?: string;
  content?: string;
  timestamp: Date;
  isAudioPlaying?: boolean;
  codeSnippet?: string; // Optional code block in message
}

export interface CodeSnippet {
  id: string;
  title: string;
  code: string;
  language: ProgrammingLanguage;
  explanation: string;
  tags: string[];
  createdAt: Date;
  complexity?: string;
}

export enum AppMode {
  SYLLABUS = 'syllabus',
  GENERAL = 'general',
  CHALLENGE = 'challenge'
}

export enum ProgrammingLanguage {
  PYTHON = 'python',
  JAVASCRIPT = 'javascript',
  TYPESCRIPT = 'typescript',
  CPP = 'cpp',
  JAVA = 'java'
}

export enum ExecutionMode {
  SCRIPT = 'script',   // User writes full code including main/imports
  FUNCTION = 'function' // User writes only the function, AI wraps it
}

export enum ExplanationStyle {
  DEFAULT = 'default',
  DEBUG = 'debug', // Find errors
  CODE_WALKTHROUGH = 'walkthrough', // Explain logic line-by-line
  OPTIMIZATION = 'optimization', // Focus on Time/Space Complexity
  SOCRATIC = 'socratic',
  ELI5 = 'eli5'
}

export enum ViewState {
  IDE = 'ide', // Main Chat + Editor
  ROADMAP = 'roadmap', // Was Graph
  CHALLENGES = 'challenges', // Was Quiz
  SNIPPETS = 'snippets', // Was Notebook
  COMMUNITY = 'community'
}

export enum AuthStage {
  LANDING = 'landing',
  LOGIN = 'login',
  REGISTER = 'register',
  DASHBOARD_SELECTION = 'dashboard_selection',
  WORKSPACE = 'workspace'
}

export interface User {
  id: string;
  name: string;
  email: string;
  isTestUser: boolean;
  streak: number;
  xp: number;
  rank: string; // Script Kiddie, Junior, Senior, Architect
  
  // Severity Stats
  problemsSolvedEasy: number;
  problemsSolvedMedium: number;
  problemsSolvedHard: number;
}

export interface Project {
  id: string;
  _id?: string;
  title: string;
  description: string;
  lastEdited: Date;
  
  // State preservation
  files: StudyFile[];
  messages: Message[];
  code: string;
  language: ProgrammingLanguage;
  snippets: CodeSnippet[];
  
  // Per-notebook data isolation
  challenges?: any[];
  roadmaps?: any[];
}

export interface Challenge {
  _id: string;
  title: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  points: number;
  topic: string;
  starterCode?: string;
  testCases?: string[];
  completed?: boolean;
  solution?: string;
}

export interface Roadmap {
  _id: string;
  title: string;
  description: string;
  nodes: GraphNode[];
  links: GraphLink[];
  progress: number;
}

export interface CodingChallenge {
  id: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  description: string;
  starterCode: string;
  testCases: string[];
}

export interface GraphNode {
  id: string;
  label: string;
  type: 'core' | 'concept' | 'detail';
  status: 'locked' | 'unlocked' | 'mastered';
  x?: number;
  y?: number;
}

export interface GraphLink {
  source: string;
  target: string;
}

export interface GraphData {
  nodes: GraphNode[];
  links: GraphLink[];
}

export interface ScanResult {
  issues: { severity: 'Important' | 'Minor', message: string, line?: number, suggestion?: string }[];
  score: number; // 0 to 100
  summary: string;
}

export interface CompletionResult {
  fixedCode: string;
  explanation: string;
}

export enum CallStatus {
  IDLE = 'idle',
  CONNECTING = 'connecting',
  ACTIVE = 'active',
  ENDING = 'ending'
}

export interface EditorTab {
  id: string;
  title: string;
  content: string;
  type: 'code' | 'diff' | 'test' | 'doc';
  isClosable: boolean;
  language?: ProgrammingLanguage; // Per-tab language support
}

export interface CommunityPost {
  id: string;
  author: string;
  title: string;
  description: string;
  likes: number;
  forks: number;
  tags: string[];
  date: string;
}

export interface ChatSession {
  id: string;
  title: string;
  messages: Message[];
  createdAt: Date;
  updatedAt: Date;
}

export interface CodeCache {
  [key: string]: { // key is language
    code: string;
    timestamp: Date;
  };
}
